### ISSUE TITLE
Clarify Stage 2 & 3

### ISSUE THREAD

**Issue by chris-aeviator** [sjunhongshen/Tag-LLM#1]
Hi! Thanks for sharing your code. I'd like to evaluate Tag LLM according to the paper. However I cannot see how the code runs 3 stages, when looking at e.g.  _Translate_ there's a Domain Training and a Cross Domain Function training, it seems as if stage 2 is skipped. 

Would I still train stage 2 or is supplying cross-domain data in stage 3 (autoregressive=False) achieving the same goal?
There are 3 config files, however only two of them show e.g. the Translate/Language training .

Would love for a quick clarification. Thanks

**Comment by sjunhongshen** [comment]
Hi! The translation task only involves 2 stages of training: training the language tags (stage 1) and training the cross-domain function tag (stage 3). This is because the translation task does not involve any single-domain functions. Thus, you can first get the language tags by 1) using domain_tag.yaml with "task_name" set to "Language", 2) creating a new directory like "exp/Translate", moving all files obtained in 1) under this directory, and 3) using function_tag.yaml with "task_name" set to "Translate", "tag_dict_path" set to "exp/Translate", and "regression" set to False.

In general, stage 2 and 3 could be parallel. If your task only involves one domain, then you only need stage 2 training; if your task involves multiple domains, then you need stage 3 training. Hope this answers your question!
